---

- name: "[RHFORUM][BREAK] Breaking the awesome Lab at Red Hat Forum Madrid 2018"
  shell: "oc new-project bad-code"

- name: "[RHFORUM][BREAK] Breaking..."
  template:
    src: "templates/nodejs-sample-pipeline-broken.yaml.j2"
    dest: "/tmp/nodejs-sample-pipeline-broken.yaml"


- name: "[RHFORUM][BREAK] Breaking the awesome Lab at Red Hat Forum Madrid 2018"
  shell: "oc create -f /tmp/nodejs-sample-pipeline-broken.yaml"

